1

diff --git a/ROMFS/px4fmu_common/init.d/rcS b/ROMFS/px4fmu_common/init.d/rcS
--- a/ROMFS/px4fmu_common/init.d/rcS
+++ b/ROMFS/px4fmu_common/init.d/rcS
@@ -245,22 +245,15 @@ else
 	fi
 
 	#
-	# Check if PX4IO present and update firmware if needed.
-	# Assumption IOFW set to firmware file and IO_PRESENT = no
+	# Start IO for PWM output or RC input if enabled
 	#
-
-	if [ -f $IOFW ]
+	if param compare -s SYS_USE_IO 1
 	then
-		# Check for the mini using build with px4io fw file
-		# but not a px4IO
-		if ver hwtypecmp V540 V560
+		# Check if PX4IO present and update firmware if needed.
+		if [ -f $IOFW ]
 		then
-			param set SYS_USE_IO 0
-		else
-			if px4io checkcrc ${IOFW}
+			if ! px4io checkcrc ${IOFW}
 			then
-				set IO_PRESENT yes
-			else
 				# tune Program PX4IO
 				tune_control play -t 16 # tune 16 = PROG_PX4IO
 
@@ -271,7 +264,6 @@ else
 					if px4io checkcrc ${IOFW}
 					then
 						tune_control play -t 17 # tune 17 = PROG_PX4IO_OK
-						set IO_PRESENT yes
 					else
 						tune_control play -t 18 # tune 18 = PROG_PX4IO_ERR
 					fi
@@ -280,20 +272,12 @@ else
 				fi
 			fi
 		fi
-	fi
 
-	#
-	# Set USE_IO flag.
-	#
-	if param compare -s SYS_USE_IO 1
-	then
-		set USE_IO yes
-	fi
-
-	if [ $USE_IO = yes -a $IO_PRESENT = no ]
-	then
-		echo "PX4IO not found"
-		tune_control play error
+		if ! px4io start
+		then
+			echo "PX4IO start failed"
+			set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
+		fi
 	fi
 
 	#
